### ISSUE TITLE
Google sign in not working

### ISSUE THREAD

**Issue by luftj** [nurdtechie98/drive-cli#99]
Using the latest pip version with any command will lead me to the following error message by google after signing in:

![grafik](https://user-images.githubusercontent.com/20200776/82822224-b6affa00-9ea5-11ea-824d-0d4a31200117.png)

Subsequently, there will be no response back to the app to tell it something failed and it gets stuck until manually sending an arbitrary request to localhost:8080

**Comment by nandzi** [comment]
[Other Drive CLIs](https://github.com/gdrive-org/gdrive/issues/533) are having the same issue, which is due to restrictions imposed by Google. I installed this app in development mode so that I could set my own oauth key and that solved the problem.

**Comment by ogrisel** [comment]
@infinitelytight  could you give more details on how to do this?

Edit: it's written in the README: https://github.com/nurdtechie98/drive-cli#installation

**Comment by nandzi** [comment]
This issue is the same as #86 by the way. In that thread, the owner of this repo said he applied for this app to be verified a few months ago, but the problem still persists.

Providing your own oauth credentials in development mode is currently a workaround but if Google refuses to verify this app then using our personal credentials should become part of the standard installation. I've checked a few similar programs and the convention is to simply ask the user to save their key somewhere like `~/.drive-cli/oauth.json`.

**Comment by luftj** [comment]
Ah, okay, thanks! I didn't see #86, closing this duplicate.
